name: astrort
channels:
  - conda-forge
  - cta-observatory
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astropy=5.1
  - asttokens=2.0.5
  - attrs=22.1.0
  - backcall=0.2.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - c-ares=1.19.1
  - ca-certificates=2023.01.10
  - cfitsio=3.430
  - comm=0.1.2
  - contourpy=1.0.5
  - ctools=2.0.0
  - curl=8.2.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.5.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - gammalib=2.0.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - healpy=1.13.0
  - icu=58.2
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.12.2
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.2.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lxml=4.9.2
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nspr=4.35
  - nss=3.89.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.10
  - packaging=23.1
  - pandas=1.3.5
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pyerfa=2.0.0
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pytest=7.1.2
  - pytest-runner=6.0.0
  - python=3.8.17
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - regions=0.7
  - scipy=1.5.3
  - seaborn=0.12.2
  - setuptools=59.8.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.2
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5

